version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_TCP_PORT: 3308
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: banco_nest
    ports:
      - '3308:3308'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: products-api
    build:
      context: ./
    image: products-api
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3308
      DB_USER: root
      DB_PASSWORD: teste
      DB_DATABASE: banco_nest
      PORT: 3000
    links:
      - db
    volumes:
      - ./:/src
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3308
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  db:
    driver: local